
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20150930 (SVN rev 66)
//----------------------------------------------------

package fuentes;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int INT1 = 23;
  public static final int CASO = 40;
  public static final int POT = 9;
  public static final int POR = 7;
  public static final int BELOWE = 13;
  public static final int SI = 37;
  public static final int ENTERO = 3;
  public static final int XOR = 18;
  public static final int CONTINUA = 44;
  public static final int HASTA = 34;
  public static final int NOT = 19;
  public static final int AND = 17;
  public static final int NAND = 20;
  public static final int SINO = 38;
  public static final int OR = 16;
  public static final int MIENTRAS = 33;
  public static final int ABOVE = 10;
  public static final int INC = 21;
  public static final int DIV = 8;
  public static final int CHAR1 = 24;
  public static final int LLAV_C = 28;
  public static final int ID = 2;
  public static final int LLAV_A = 27;
  public static final int PYCOMA = 30;
  public static final int EOF = 0;
  public static final int DECIMAL = 4;
  public static final int ASIG = 32;
  public static final int EQUAL = 14;
  public static final int error = 1;
  public static final int COMA = 29;
  public static final int MENOS = 6;
  public static final int SELEC = 39;
  public static final int PAR_C = 26;
  public static final int PAR_A = 25;
  public static final int ABOVEE = 12;
  public static final int DETENER = 43;
  public static final int BELOW = 11;
  public static final int NEQUAL = 15;
  public static final int DPUNTO = 31;
  public static final int REPETIR = 35;
  public static final int HACER = 36;
  public static final int PARA = 42;
  public static final int DEC = 22;
  public static final int DEFECTO = 41;
  public static final int MAS = 5;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "ID",
  "ENTERO",
  "DECIMAL",
  "MAS",
  "MENOS",
  "POR",
  "DIV",
  "POT",
  "ABOVE",
  "BELOW",
  "ABOVEE",
  "BELOWE",
  "EQUAL",
  "NEQUAL",
  "OR",
  "AND",
  "XOR",
  "NOT",
  "NAND",
  "INC",
  "DEC",
  "INT1",
  "CHAR1",
  "PAR_A",
  "PAR_C",
  "LLAV_A",
  "LLAV_C",
  "COMA",
  "PYCOMA",
  "DPUNTO",
  "ASIG",
  "MIENTRAS",
  "HASTA",
  "REPETIR",
  "HACER",
  "SI",
  "SINO",
  "SELEC",
  "CASO",
  "DEFECTO",
  "PARA",
  "DETENER",
  "CONTINUA"
  };
}

