
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20150930 (SVN rev 66)
//----------------------------------------------------

package fuentes;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int PAR_A = 6;
  public static final int COMA = 8;
  public static final int STRUCT = 5;
  public static final int EOF = 0;
  public static final int INT1 = 3;
  public static final int ID = 2;
  public static final int error = 1;
  public static final int CHAR1 = 4;
  public static final int DPUNTOS = 9;
  public static final int PYCOMA = 10;
  public static final int PAR_C = 7;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "ID",
  "INT1",
  "CHAR1",
  "STRUCT",
  "PAR_A",
  "PAR_C",
  "COMA",
  "DPUNTOS",
  "PYCOMA"
  };
}

